 <?php
 $countries = array(
            array(  "name" => "isp",
                    "country" => "Испания",
                    "capital" => "Барселона",
                    "capital_image" => "barselona.jpg",
                    "image" => "ispania_planet.png",
                    "flag" => "isp.jpg",
                    "info" => "Ispania.html",
                    "map" => "ispania2.jpg",
                ),
            array(  "name" => "eng",
                    "country" => "Англия",
                    "capital" => "Лондон",
                    "capital_image" => "london.jpg",
                    "image" => "england_planet.png",
                    "flag" => "eng.png",
                    "info" => "England.html",
                    "map" => "England2.jpg",
                ),
            array(  "name" => "fran",
                    "country" => "Франция",
                    "capital" => "Париж",
                    "capital_image" => "paris.jpg",
                    "image" => "france_planet.png",
                    "flag" => "fran.jpg",
                    "info" => "France.html",
                    "map" => "france2.jpg",
                ),
            array(  "name" => "est",
                    "country" => "Эстония",
                    "capital" => "Таллин",
                    "capital_image" => "tallin.jpg",
                    "image" => "estonia_planet.png",
                    "flag" => "est.jpg",
                    "info" => "Eesti.html",
                    "map" => "eesti2.jpg",
                )
     );
 
?>